#pragma once

#include <string>
#include <vector>
#include <cstdint>

constexpr int MAX_MAP_ZONE_NAME = 27;
constexpr int INVALID_MAP_ZONE_ID = -1;
constexpr int EXCLUDED_MAP_ZONE_AREA_COUNT = 9;
constexpr int MAX_MAP_ZONE_AREAS = 13;

enum class MapZone : int {
    ZONE_BAYSIDE_MARINA = 0,
    ZONE_BAYSIDE,
    ZONE_BATTERY_POINT,
    ZONE_PARADISO,
    ZONE_SANTA_FLORA,
    ZONE_PALISADES,
    ZONE_CITY_HALL,
    ZONE_OCEAN_FLATS,
    ZONE_FOSTER_VALLEY,
    ZONE_HASHBURY,
    ZONE_JUNIPER_HOLLOW,
    ZONE_ESPLANADE_NORTH,
    ZONE_FINANCIAL,
    ZONE_CALTON_HEIGHTS,
    ZONE_DOWNTOWN,
    ZONE_JUNIPER_HILL,
    ZONE_CHINATOWN,
    ZONE_KINGS,
    ZONE_GARCIA,
    ZONE_DOHERTY,
    ZONE_EASTER_BAY_AIRPORT,
    ZONE_EASTER_BASIN,
    ZONE_ESPLANADE_EAST,
    ZONE_ANGEL_PINE,
    ZONE_SHADY_CABIN,
    ZONE_BACK_O_BEYOND,
    ZONE_LEAFY_HOLLOW,
    ZONE_FLINT_RANGE,
    ZONE_FALLEN_TREE,
    ZONE_THE_FARM,
    ZONE_EL_QUEBRADOS,
    ZONE_ALDEA_MALVADA,
    ZONE_THE_SHERMAN_DAM,
    ZONE_LAS_BARRANCAS,
    ZONE_FORT_CARSON,
    ZONE_HUNTER_QUARRY,
    ZONE_OCTANE_SPRINGS,
    ZONE_GREEN_PALMS,
    ZONE_REGULAR_TOM,
    ZONE_LAS_BRUJAS,
    ZONE_VERDANT_MEADOWS,
    ZONE_LAS_PAYASADAS,
    ZONE_ARCO_DEL_OESTE,
    ZONE_HANKYPANKY_POINT,
    ZONE_PALOMINO_CREEK,
    ZONE_NORTH_ROCK,
    ZONE_MONTGOMERY,
    ZONE_HAMPTON_BARNS,
    ZONE_FERN_RIDGE,
    ZONE_DILLIMORE,
    ZONE_HILLTOP_FARM,
    ZONE_BLUEBERRY,
    ZONE_THE_PANOPTICON,
    ZONE_FREDERICK_BRIDGE,
    ZONE_THE_MAKO_SPAN,
    ZONE_BLUEBERRY_ACRES,
    ZONE_MARTIN_BRIDGE,
    ZONE_FALLOW_BRIDGE,
    ZONE_SHADY_CREEKS,
    ZONE_QUEENS,
    ZONE_GANT_BRIDGE,
    ZONE_EASTER_BAY_CHEMICALS,
    ZONE_LOS_SANTOS_INTERNATIONAL,
    ZONE_VERDANT_BLUFFS,
    ZONE_EL_CORONA,
    ZONE_WILLOWFIELD,
    ZONE_OCEAN_DOCKS,
    ZONE_MARINA,
    ZONE_VERONA_BEACH,
    ZONE_CONFERENCE_CENTER,
    ZONE_COMMERCE,
    ZONE_PERSHING_SQUARE,
    ZONE_LITTLE_MEXICO,
    ZONE_IDLEWOOD,
    ZONE_GLEN_PARK,
    ZONE_JEFFERSON,
    ZONE_LAS_COLINAS,
    ZONE_GANTON,
    ZONE_EAST_BEACH,
    ZONE_EAST_LOS_SANTOS,
    ZONE_LOS_FLORES,
    ZONE_DOWNTOWN_LOS_SANTOS,
    ZONE_MULHOLLAND_INTERSECTION,
    ZONE_MULHOLLAND,
    ZONE_MARKET,
    ZONE_VINEWOOD,
    ZONE_TEMPLE,
    ZONE_SANTA_MARIA_BEACH,
    ZONE_RODEO,
    ZONE_RICHMAN,
    ZONE_THE_STRIP,
    ZONE_THE_FOUR_DRAGONS_CASINO,
    ZONE_THE_PINK_SWAN,
    ZONE_THE_HIGH_ROLLER,
    ZONE_PIRATES_IN_MENS_PANTS,
    ZONE_THE_VISAGE,
    ZONE_JULIUS_THRUWAY_SOUTH,
    ZONE_JULIUS_THRUWAY_WEST,
    ZONE_ROCKSHORE_EAST,
    ZONE_COMEALOT,
    ZONE_THE_CAMELS_TOE,
    ZONE_ROYAL_CASINO,
    ZONE_CALIGULAS_PALACE,
    ZONE_PILGRIM,
    ZONE_STARFISH_CASINO,
    ZONE_THE_EMERALD_ISLE,
    ZONE_OLD_VENTURAS_STRIP,
    ZONE_KACC_MILITARY_FUELS,
    ZONE_CREEK,
    ZONE_SOBELL_RAIL_YARDS,
    ZONE_LINDEN_STATION,
    ZONE_JULIUS_THRUWAY_EAST,
    ZONE_LINDEN_SIDE,
    ZONE_JULIUS_THRUWAY_NORTH,
    ZONE_HARRY_GOLD_PARKWAY,
    ZONE_REDSANDS_EAST,
    ZONE_REDSANDS_WEST,
    ZONE_LAS_VENTURAS_AIRPORT,
    ZONE_LVA_FREIGHT_DEPOT,
    ZONE_BLACKFIELD_INTERSECTION,
    ZONE_GREENGLASS_COLLEGE,
    ZONE_BLACKFIELD,
    ZONE_ROCA_ESCALANTE,
    ZONE_LAST_DIME_MOTEL,
    ZONE_ROCKSHORE_WEST,
    ZONE_RANDOLPH_INDUSTRIAL_ESTATE,
    ZONE_BLACKFIELD_CHAPEL,
    ZONE_PILSON_INTERSECTION,
    ZONE_WHITEWOOD_ESTATES,
    ZONE_PRICKLE_PINE,
    ZONE_SPINYBED,
    ZONE_SAN_ANDREAS_SOUND,
    ZONE_FISHERS_LAGOON,
    ZONE_GARVER_BRIDGE,
    ZONE_KINCAID_BRIDGE,
    ZONE_LOS_SANTOS_INLET,
    ZONE_SHERMAN_RESERVOIR,
    ZONE_FLINT_WATER,
    ZONE_EASTER_TUNNEL,
    ZONE_BAYSIDE_TUNNEL,
    ZONE_THE_BIG_EAR,
    ZONE_LIL_PROBE_INN,
    ZONE_VALLE_OCULTADO,
    ZONE_UNITY_STATION,
    ZONE_MARKET_STATION,
    ZONE_CRANBERRY_STATION,
    ZONE_YELLOW_BELL_STATION,
    ZONE_SAN_FIERRO_BAY,
    ZONE_EL_CASTILLO_DEL_DIABLO,
    ZONE_RESTRICTED_AREA,
    ZONE_MONTGOMERY_INTERSECTION,
    ZONE_ROBADA_INTERSECTION,
    ZONE_FLINT_INTERSECTION,
    ZONE_AVISPA_COUNTRY_CLUB,
    ZONE_MISSIONARY_HILL,
    ZONE_MOUNT_CHILIAD,
    ZONE_YELLOW_BELL_GOLF_COURSE,
    ZONE_BEACON_HILL,
    ZONE_PLAYA_DEL_SEVILLE,
    ZONE_THE_CLOWNS_POCKET,
    ZONE_LOS_SANTOS,
    ZONE_LAS_VENTURAS,
    ZONE_BONE_COUNTY,
    ZONE_TIERRA_ROBADA,
    ZONE_SAN_FIERRO,
    ZONE_RED_COUNTY,
    ZONE_FLINT_COUNTY,
    ZONE_WHETSTONE
};

struct MapZoneData {
    std::string name;
    int soundId;
    int areaCount;
};

struct MapZoneAreaData {
    MapZone id;
    float minX, minY, minZ;
    float maxX, maxY, maxZ;
};

class MapZones {
public:
    static MapZone GetMapZoneAtPoint(float x, float y, float z);
    static MapZone GetMapZoneAtPoint2D(float x, float y);
    static int GetMapZoneCount();
    static bool IsValidMapZone(MapZone id);
    static std::string GetMapZoneName(MapZone id);
    static bool GetMapZoneSoundID(MapZone id, int& soundId);
    static bool GetMapZoneAreaCount(MapZone id, int& count);
    static int GetMapZoneAreaPos(MapZone id, float& minX, float& minY, float& minZ, 
                                float& maxX, float& maxY, float& maxZ, int start = 0);

private:
    static int GetMapZoneLoopStartIndex(float x);
    static const std::vector<MapZoneData>& GetMapZoneDataTable();
    static const std::vector<MapZoneAreaData>& GetMapZoneAreaDataTable();
};